// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBf_1z3TCYSOCmcifkw2TpS3vNxVWF4OrI',
    appId: '1:285824147268:web:56413351c64c372c48c111',
    messagingSenderId: '285824147268',
    projectId: 'saarthi-728ba',
    authDomain: 'saarthi-728ba.firebaseapp.com',
    storageBucket: 'saarthi-728ba.appspot.com',
    measurementId: 'G-V097XF2LGV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzDEOHqR4Ut7ZlIvby9ycJn6dIQeaIS-8',
    appId: '1:285824147268:android:8008fbf9e7df3c7a48c111',
    messagingSenderId: '285824147268',
    projectId: 'saarthi-728ba',
    storageBucket: 'saarthi-728ba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgNj10AO3Ddl72TWWLwnid3cLkbefIYEk',
    appId: '1:285824147268:ios:df246d9ac865c61848c111',
    messagingSenderId: '285824147268',
    projectId: 'saarthi-728ba',
    storageBucket: 'saarthi-728ba.appspot.com',
    iosBundleId: 'com.example.saarthi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgNj10AO3Ddl72TWWLwnid3cLkbefIYEk',
    appId: '1:285824147268:ios:35f2560202bdcdf448c111',
    messagingSenderId: '285824147268',
    projectId: 'saarthi-728ba',
    storageBucket: 'saarthi-728ba.appspot.com',
    iosBundleId: 'com.example.saarthi.RunnerTests',
  );
}
